name: ROS 2 Jazzy CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble  # Matches Ubuntu 24.04 for Jazzy

    steps:
      - uses: actions/checkout@v4

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: custom_action_interfaces
          target-ros2-distro: jazzy
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "release"]
              }
            }
