name: ROS 2 Jazzy CI with Dependency Management

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble  # Matches Ubuntu 24.04 for Jazzy

    steps:
      - uses: actions/checkout@v4

      - name: Create Workspace Structure
        run: |
          mkdir -p src
          cp -r ./* src/  # Copy all files to src if not already structured

      - name: Install System Dependencies
        run: |
          apt-get update && apt-get install -y \
            python3-rosdep \
            build-essential \
            cmake

      - name: Initialize and Update rosdep
        run: |
          rosdep init (if not already initialized)
          rosdep update

      - name: Install Package Dependencies
        working-directory: .
        run: |
          if [ -f "install_rosdeps.sh" ]; then
            bash -c "./install_rosdeps.sh jazzy"
          else
            echo "install_rosdeps.sh not found, using default rosdep"
            rosdep install --from-paths src --ignore-src -r -y
          fi

      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: custom_action_interfaces
          target-ros2-distro: jazzy
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc", "release"]
              }
            }

      - name: Check for Unmet Dependencies
        working-directory: .
        run: |
          if ! rosdep check --from-paths src --ignore-src; then
            echo "Unmet dependencies found. Please ensure all dependencies in package.xml are available in ROS 2 Jazzy."
            exit 1
          fi
